# Ours
data:
  type: semantic_seg
  model_save_dir: /home/native/projects/data/cranberry/models/
  models_lists_dir: /home/native/projects/data/cranberry/models/cranberry_segmentation
  model_name: /home/native/projects/data/cranberry/models/floodfill/training_floodfill_instance_count_count_detect_seg_3.0_instance_3.0_convexity_10.0_circularity_10.0_count_0.2_2020-03-09-10:03 - baseline/floodfill_epoch_43_mean_iou_0.6254406128186686_best_mae_13.459821428571429_mioumao_ratio_4.646722960908185_time_2020-03-09-13:23:56.pth
  eval_dir: /media/native/data/data/CRAID1/
  has_mask: True
  val_dir:
  image_size: 456x608

testing: 
  learning_rate: 0.004 #1e-4
  resume: /home/native/projects/data/cranberry/models/floodfill/training_floodfill_instance_count_count_detect_seg_3.0_instance_3.0_convexity_10.0_circularity_10.0_count_0.2_2020-03-09-10:03 - baseline/floodfill_epoch_43_mean_iou_0.6254406128186686_best_mae_13.459821428571429_mioumao_ratio_4.646722960908185_time_2020-03-09-13:23:56.pth
  train_val_test_split: [0.9,0.05,0.05]
  epochs: 300
  batch_size: 1
  drop_last_batch:
  optimizer:
  num_workers: 1
  img_only: False

use_cuda: True
lambda:
threads: 
no_data_augm:
val_freq:
seed:
log_interval:
max_trainset_size:
max_valset_size:
max_mask_points: 
radius:
n_points: