# Ours
location: docker #[local, docker]
data:
  image_size: 456x608
  local:
    type: semantic_seg
    model_save_dir: /home/native/projects/data/cranberry/models/
    train_dir: /home/native/projects/data/cranberry/points/instance_points/
    test_dir: /home/native/projects/data/cranberry/semantic_seg/
    val_dir:
  docker:
    type: semantic_seg
    model_save_dir: /app/finding_berries/models/
    train_dir: /app/finding_berries/data/instance_points/
    test_dir: /app/finding_berries/data/semantic_seg/
    val_dir:

training: 
  learning_rate: 0.001 #1e-4
  # resume: /home/native/projects/data/cranberry/models/floodfill/training_floodfill_instance_circularity_count_count_detect_seg_3.0_instance_3.0_convexity_10.0_circularity_10.0_count_0.2_2020-03-09-10:09 - baseline/floodfill_epoch_37_mean_iou_0.6588786266672169_best_mae_14.308035714285714_mioumao_ratio_4.604955144257616_time_2020-03-09-13:13:32.pth
  resume: False
  train_val_test_split: [0.9,0.05,0.05]
  epochs: 200
  batch_size: 1
  drop_last_batch:
  optimizer:
  num_workers: 1
  # loss_weights: {seg: 0.03, instance: 0.5, convexity: 100.0, circularity: 1.0, count: 1000.0}
  loss_weights: {seg: 3.0, instance: 3.0, convexity: 10.0, circularity: 10.0, count: 0.2}
  class_weights: {seg: [1,3000,'mean'], instance: [60,1,'mean']}
  # losses_to_use: ["count"]
  # losses_to_use: ["insatnce"]
  # losses_to_use: ["instance","count_detect"]
  # losses_to_use: ["instance","count", "count_detect"]
  # losses_to_use: ["instance","count", "count_regress"]
  # losses_to_use: ["instance","circularity","count", "count_detect"]
  losses_to_use: ["instance","circularity", "count_detect"]
  # losses_to_use: ["instance","convexity","count_detect"]
  # losses_to_use: ["instance","convexity","count","count_detect"]
  # losses_to_use: ["instance","circularity","convexity","count_detect"]
  # losses_to_use: ["circularity","count"]
  # losses_to_use: ["convexity","count"]
  # losses_to_use: ["convexity"]
  # losses_to_use: ["circularity","convexity","count"]
  # losses_to_use: ["count_detect"]
  test_with_full_supervision: 1
  # test_with_full_supervision: 0

use_cuda: True
cometml_api_key: apikey
lambda:
threads: 
no_data_augm:
val_freq:
seed:
log_interval:
max_trainset_size:
max_valset_size:
max_mask_points: 
radius:
n_points:
