# Ours
data:
  type: semantic_seg
  model_save_dir: /home/native/projects/data/cranberry/models/
  models_lists_dir: /home/native/projects/data/cranberry/models/cranberry_segmentation
  model_name: /home/native/projects/data/cranberry/models/cranberry_segmentation/cranberry_counting_cranberry_segmentation_2020-02-04-13:43/cranberry_segmentation_epoch_92_mAP_0.8028254846226599_time_2020-02-04-13:43:02.pth
  eval_dir: /home/native/projects/data/cranberry/semantic_seg/
  has_mask: True
  val_dir:
  image_size: 456x608

testing: 
  learning_rate: 0.004 #1e-4
  resume: /home/native/projects/data/cranberry/models/cranberry_segmentation/cranberry_counting_cranberry_segmentation_2020-02-04-13:43/cranberry_segmentation_epoch_92_mAP_0.8028254846226599_time_2020-02-04-13:43:02.pth
  train_val_test_split: [0.9,0.05,0.05]
  epochs: 300
  batch_size: 1
  drop_last_batch:
  optimizer:
  num_workers: 1
  img_only: False

use_cuda: True
lambda:
threads: 
no_data_augm:
val_freq:
seed:
log_interval:
max_trainset_size:
max_valset_size:
max_mask_points: 
radius:
n_points: